In [ ]:
!pip install pandas requests duckdb ratelimit

In [1]:
import pandas as pd 
import requests 
import pandas as pd 
import duckdb
import os
from ratelimit import limits, sleep_and_retry

In [2]:
api_key = os.environ.get("TMDB_APIKEY")
if not api_key:
   raise ValueError("API KEY missing")

In [3]:
headers = {"accept": "application/json", "Authorization": f"Bearer {api_key}"}
# movie_url = f"https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&primary_release_date.gte=2024-01-01&sort_by=popularity.desc&vote_average.gte=7&vote_count.gte=1000"
tv_url = "https://api.themoviedb.org/3/discover/tv?include_adult=false&include_null_first_air_dates=false&language=en-US&page=1&sort_by=popularity.desc"
persons_url = "https://api.themoviedb.org/3/person/popular?language=en-US&page=1"

In [4]:
@sleep_and_retry
@limits(calls = 25, period = 1)
def extract_movie_ids(date = "2024-01-01", rating=7.0, votes=1000, max_pages=10):
    """
    Extract movie_ids from TMDB API. This method is better bcos it allows getting more movie info from movie details on tmdb
    
    Args:
        date (str): The minimum release date of the movies to be fetched. Format: YYYY-MM-DD
        rating (float): The minimum average rating of the movies to be fetched.
        votes (int): The minimum number of votes of the movies to be fetched.
        max_pages (int): The maximum number of pages to fetch. Each page contains 20 movies.
        """
        
    date = str(date)
    rating = float(rating)
    votes = int(votes)
    max_pages =int(max_pages)

    movie_url = f"https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&primary_release_date.gte={date}&sort_by=popularity.desc&vote_average.gte={rating}&vote_count.gte={votes}"
    
    response = requests.get(url=movie_url, headers=headers)
    data = response.json()
    total_pages = data.get("total_pages")
    if total_pages > max_pages:
        print(f"Requesting too many pages. The maximum is {max_pages} pages. Stopping fetch.")
        return        
    
    try:
        all_movies = []
        for num in range(1, total_pages + 1):
            movie_url = f"https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page={num}&primary_release_date.gte={date}&sort_by=popularity.desc&vote_average.gte={rating}&vote_count.gte={votes}"

            response = requests.get(url=movie_url, headers=headers)

            data = response.json()
            movies_on_page = data.get("results", [])
            all_movies.extend(movies_on_page)
        
        ids = [all_movies[x].get('id') for x in range(len(all_movies))]
        return list(dict.fromkeys(ids)) # checking that the ids are not duplicates by converting it to dict and back to list. dict disallows duplicates and retains order
                
            # print(f"Fetched page {num} of {total_pages}") 
    except Exception as e:
        print(f'An unexpected error occured: {e}')
    
# movie_ids = extract_movie_ids()

In [5]:
# # len(all_movies)
# movie_ids = [all_movies[x].get('id') for x in range(len(all_movies))]
# len(list(dict.fromkeys(movie_ids)))
len(movie_ids)

105

In [6]:
@sleep_and_retry
@limits(calls=25, period=1)
def extract_movie_details():
    """
    Extracting movie details using the movie id
    """
    movie_ids = extract_movie_ids()
    details = []
    for movie_id in movie_ids:
        try:
            url = f"https://api.themoviedb.org/3/movie/{movie_id}?language=en-US"
            response = requests.get(url=url, headers=headers)
            data = response.json()
            details.append(data)
        except Exception as e:
            print(f'An unexpected error occured: {e}')
    return details

movie_details= extract_movie_details()

In [7]:
movie_details[0]

{'adult': False,
 'backdrop_path': '/r08LxMJCbf1SiJIWeyH9aJmdqwC.jpg',
 'belongs_to_collection': {'id': 531241,
  'name': 'Spider-Man (MCU) Collection',
  'poster_path': '/yeba3Y820OjApZO9aJevDsNeMEd.jpg',
  'backdrop_path': '/AvnqpRwlEaYNVL6wzC4RN94EdSd.jpg'},
 'budget': 225000000,
 'genres': [{'id': 878, 'name': 'Science Fiction'},
  {'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'}],
 'homepage': 'https://spidermanbrandnewday.movie',
 'id': 969681,
 'imdb_id': 'tt22084616',
 'origin_country': ['US'],
 'original_language': 'en',
 'original_title': 'Spider-Man: Brand New Day',
 'overview': "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.",
 'popularity': 655.4447,
 'poster_path': '/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg',
 'production_companies': [{'id': 420,
   'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
   'name': 'Marvel Studios',
   'origin_country': 'US'},
  {'id': 5,
   'logo_path': '/71BqEFAF4V3qjjMPCpLuyJFB9A.png',
   'name': 'Columbia Pictures',
   'origin_country': 'US'},
  {'id': 84041,
   'logo_path': '/nw4kyc29QRpNtFbdsBHkRSFavvt.png',
   'name': 'Pascal Pictures',
   'origin_country': 'US'},
  {'id': 22213,
   'logo_path': '/qx9K6bFWJupwde0xQDwOvXkOaL8.png',
   'name': 'TSG Entertainment',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '2026-07-29',
 'revenue': 2516291000,
 'runtime': 145,
 'softcore': False,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'}],
 'status': 'Released',
 'tagline': 'A brand new day starts now.',
 'title': 'Spider-Man: Brand New Day',
 'video': False,
 'vote_average': 8.468,
 'vote_count': 5723}

In [48]:
movie_details_df = pd.DataFrame(movie_details)
movie_details_df.columns

Index(['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres',
       'homepage', 'id', 'imdb_id', 'origin_country', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'softcore', 'spoken_languages', 'status',
       'tagline', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='str')

In [49]:
movie_details_df.drop(columns = ['adult','homepage', 'belongs_to_collection', 'imdb_id', 'origin_country', 'original_title',  'production_countries', 'softcore', 'spoken_languages', 'video'], inplace=True)  
movie_details_df.head(3)

,backdrop_path,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,release_date,revenue,runtime,status,tagline,title,vote_average,vote_count
0,/4tjxYg2AbOzzG9G1YuiT2NzYhlH.jpg,225000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",969681,en,Fighting crime full-time as Spider-Man in a wo...,768.8287,/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2026-07-29,2512865567,145,Released,A brand new day starts now.,Spider-Man: Brand New Day,8.460,5457
1,/twiVn9oFXOVR0uoYgawyEBlnFu8.jpg,250000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",1368337,en,"Odysseus, the legendary King of Ithaca, embark...",379.5091,/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,"[{'id': 33, 'logo_path': '/8lvHyhjr8oUKOOy2dKX...",2026-07-15,1779770790,173,Released,Defy the gods.,The Odyssey,8.000,4129
2,/qjTqY5coNiz6sVtPng40IzltsoN.jpg,250000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",1084244,en,When Bonnie receives a Lilypad tablet as a gif...,162.0222,/sfQtVlIHljToOwYjhe21KPGzZWK.jpg,"[{'id': 3, 'logo_path': '/1TjvGVDMYsj6JBxOAkUH...",2026-06-17,1148032461,102,Released,It's on.,Toy Story 5,8.287,2606

In [ ]:
# movie_details_df['genres'] = movie_details_df['genres'].apply(lambda x: [d['id'] for d in x])
# movie_details_df['production_companies'] = movie_details_df['production_companies'].apply(lambda x: [d['id'] for d in x])
movie_details_df['popularity']

0      768.8287
1      379.5091
2      162.0222
3      149.1721
4      175.5056
         ...
100     11.7493
101     17.2964
102     10.6681
103     10.4793
104     22.2002
Name: popularity, Length: 105, dtype: float64

In [51]:
extracted_genres = [genre for x in range(len(movie_details)) for genre in movie_details[x]['genres']]
extracted_prod_companies = [company for x in range(len(movie_details)) for company in movie_details[x]['production_companies']]
dim_genre_df = pd.DataFrame(extracted_genres).drop_duplicates().reset_index(drop=True)
dim_prod_company_df = pd.DataFrame(extracted_prod_companies).drop_duplicates().reset_index(drop=True)[['id', 'name']]
dim_genre_df.head(3)

    id             name
0  878  Science Fiction
1   28           Action
2   12        Adventure

In [60]:
movie_details_df['date'] = movie_details_df['release_date'].apply(lambda x: x.replace('-', ''))
movie_details_df['date'].head(2)

0    20260729
1    20260715
Name: date, dtype: str

In [56]:
with duckdb.connect("movies_warehouse.duckdb") as con: 
    con.execute("""
        CREATE TABLE IF NOT EXISTS dim_date (
            date_id INTEGER PRIMARY KEY,
            full_date DATE,
            year INTEGER,
            quarter INTEGER,
            month INTEGER, 
            month_name VARCHAR,
            day_of_week VARCHAR,
            is_weekend BOOLEAN
        );

        CREATE TABLE IF NOT EXISTS dim_genre (
            genre_id INTEGER PRIMARY KEY,
            genre_name VARCHAR
        );

        CREATE TABLE IF NOT EXISTS dim_movie (
            movie_id INTEGER PRIMARY KEY,
            title VARCHAR,
            overview TEXT,
            tagline TEXT,
            original_language VARCHAR,
            status VARCHAR,
            poster_path VARCHAR,
            production_company_ids INTEGER[],
            genre_ids INTEGER[] 
        );

        CREATE TABLE IF NOT EXISTS fact_movie (
            movie_id INTEGER PRIMARY KEY,
            release_date_id INTEGER,
            runtime INTEGER, 
            vote_average DECIMAL(3,1),
            vote_count INTEGER,
            popularity DECIMAL(10,3),
            budget INTEGER,
            revenue BIGINT
            
        );

        CREATE TABLE IF NOT EXISTS dim_production_company (
            production_company_id INTEGER PRIMARY KEY,
            production_company_name VARCHAR
        );
        """
)

In [68]:
with duckdb.connect("movies_warehouse.duckdb") as con:
    print(con.execute("SHOW TABLES;").df())

                     name
0                dim_date
1               dim_genre
2               dim_movie
3  dim_production_company
4              fact_movie

In [39]:
# dim_genre_df.head(3)
dim_prod_company_df.head(3)

      id               name
0    420     Marvel Studios
1      5  Columbia Pictures
2  84041    Pascal Pictures

Loading into database

In [71]:
with duckdb.connect("movies_warehouse.duckdb") as con:
    con.register("dim_genre_df", dim_genre_df)
    con.register('dim_prod_company_df', dim_prod_company_df)
    con.register('movie_details_df', movie_details_df)
    con.execute("""
        INSERT OR IGNORE INTO dim_genre (genre_id, genre_name)
        SELECT
            id::INTEGER as genre_id,
            name::VARCHAR as genre_name
        FROM dim_genre_df;

        
        INSERT OR IGNORE INTO dim_production_company (production_company_id, production_company_name)
        SELECT         
            id::INTEGER as production_company_id,
            name::VARCHAR as production_company_name
        FROM dim_prod_company_df;

        
        INSERT OR REPLACE INTO dim_movie(movie_id, title, overview, tagline, original_language, status, poster_path, production_company_ids, genre_ids)
        SELECT 
            id::INTEGER as movie_id,
            title::VARCHAR as title,
            overview::TEXT as overview,
            tagline::TEXT as tagline,
            original_language::VARCHAR as original_language,
            status::VARCHAR as status,
            poster_path::VARCHAR as poster_path,
            production_companies::INTEGER[] as production_company_ids,
            genres::INTEGER[] as genre_ids
        FROM movie_details_df;

        
        INSERT OR REPLACE INTO fact_movie(movie_id, release_date_id, runtime, vote_average, vote_count, popularity, budget, revenue)
        SELECT 
            id::INTEGER as movie_id,
            date::INTEGER as release_date_id,
            runtime::INTEGER as runtime,
            vote_average::DECIMAL(3,1) as vote_average,
            vote_count::INTEGER as vote_count,
            popularity::DECIMAL(10,3) as popularity,
            budget::INTEGER as budget,
            revenue::BIGINT as revenue
        FROM movie_details_df;


        INSERT OR IGNORE INTO dim_date(date_id, full_date, year, quarter, month, month_name, day_of_week, is_weekend)
        SELECT 
            date::INTEGER as date_id,
            release_date::DATE as full_date,
            year(release_date::DATE) as year,
            quarter(release_date::DATE) as quarter,
            month(release_date::DATE) as month,
            strftime(release_date::DATE, '%B') as month_name,
            strftime(release_date::DATE, '%w') as day_of_week,
            CASE WHEN EXTRACT(DOW FROM release_date::DATE) IN (0, 6) THEN TRUE ELSE FALSE END as is_weekend
        FROM movie_details_df

""")
    print("Insert Successful!!")

Insert Successful!!

In [ ]:
with duckdb.connect("movies_warehouse.duckdb") as con:
    con.register("df_view", movie_df)
    con.execute("""
        INSERT INTO dim_movie (movie_id, title, overview, original_language, poster_path, genre_ids)
        SELECT 
            id::INTEGER as movie_id,
            title,
            overview,
            original_language,
            backdrop_path as poster_path,
            genre_ids::INTEGER[] as genre_ids
        FROM df_view
        """)

In [4]:
import duckdb
import pandas as pd
con = duckdb.connect("movies_warehouse.duckdb")
con.execute("""
    select * from dim_movie
    limit 5
    """).df()

,movie_id,title,overview,tagline,original_language,status,poster_path,production_company_ids,genre_ids
0,969681,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,None,en,None,/subj7knTn4DeS6KS7qI66EQKe9i.jpg,<NA>,"[878, 28, 12]"
1,1368337,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",None,en,None,/twiVn9oFXOVR0uoYgawyEBlnFu8.jpg,<NA>,"[12, 28, 14]"
2,1101383,The End of Oak Street,After a mysterious cosmic event rips Oak Stree...,None,en,None,/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg,<NA>,"[878, 9648, 53]"
3,1084244,Toy Story 5,When Bonnie receives a Lilypad tablet as a gif...,None,en,None,/qjTqY5coNiz6sVtPng40IzltsoN.jpg,<NA>,"[16, 10751, 35, 12]"
4,1339713,Obsession,"After breaking the mysterious ""One Wish Willow...",None,en,None,/5lTZyuBTNOfawsfPT8Q0cIg6qAF.jpg,<NA>,"[27, 53]"

In [ ]:
try:
    response = requests.get(url=movie_url, headers=headers)
    data= response.json()
except Exception as e:
    print(f'An unexpected error occured: {e}')

In [7]:
import requests
networks = []
for network_id in range(555, 558):
    url = f"https://api.themoviedb.org/3/network/{network_id}"

# headers = {
#     "accept": "application/json",
#     "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxNjZiNTdhMTBkMTQyNmVmMTQ0NGJmNTFjODBkYzg5ZSIsIm5iZiI6MTc5MTY0OTI0MC42ODQsInN1YiI6IjZhY2E2NWQ4NzdhMjhiYmQxOGYwZmU4YyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.uxXhuUGB1Klf9jpXfjREL4WEIwMxRP1sVlVj-jz8CKA"
# }

    response = requests.get(url, headers=headers)
    # network_respon
    print(response.text)

{"headquarters":"","homepage":"http://www.tvp.pl/","id":555,"logo_path":"/oq606JVmXAWtp6BeUqSSFdsp64O.png","name":"TVP","origin_country":"PL"}
{"headquarters":"Vilvoorde","homepage":"http://www.vtm.be","id":556,"logo_path":"/wpPJM99T9qkKvK16nRciNL2y64Q.png","name":"VTM","origin_country":"BE"}
{"headquarters":"","homepage":"","id":557,"logo_path":null,"name":"Community Channel","origin_country":"GB"}

In [27]:
data['results'][1].keys()

dict_keys(['adult', 'backdrop_path', 'genre_ids', 'id', 'title', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'release_date', 'softcore', 'video', 'vote_average', 'vote_count'])

In [ ]:
import pandas as pd 
import duckdb
import time

# df = pd.DataFrame(data['results'])
#df.head()

## Create the Star Schema tables

In [ ]:
# [item for item in dir(response) if not item.startswith("_") and not callable(getattr(response, item))]

In [ ]:
# BASE_URL = 'https://api.aviationstack.com/v1/'

# api_key = os.environ.get("AVIATIONSTACK_APIKEY")

# if api_key:
#     print(f"Secret found: {api_key[:4]}...")
# else:
#     print("Secret not found")

Secret found: 318c...

In [ ]:
all_movies = []

@sleep_and_retry
@limits(calls=25, period=1)
def extract_top_movies(date: str = "2024-01-01", rating: float = 7.0, voters: int = 1000, num_pages=6):
    """
    Extracting top movies released after 1st January 2024 with an average rating greater than 7.0 with not less than 1000 rating votes 
    """
    try:

        movie_url = f"https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&primary_release_date.gte={date}&sort_by=popularity.desc&vote_average.gte={rating}&vote_count.gte={voters}"

        for num in range(1, num_pages + 1):
            response = requests.get(url=movie_url, headers=headers)

            data = response.json()
            movies_on_page = data.get("results", [])
            all_movies.extend(movies_on_page)
                
            print(f"Fetched page {num} of {num_pages}")      
        return 
    except Exception as e:
        print(f'An unexpected error occured: {e}')

extract_top_movies()

Fetched page 1 of 6
Fetched page 2 of 6
Fetched page 3 of 6
Fetched page 4 of 6
Fetched page 5 of 6
Fetched page 6 of 6